### ISSUE TITLE
[Reporting] Got Landscape PDF for a Potrait Supposed PDF 

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#20]
### Problem
How to replicate:
- Load test layers
- Run analysis on Volcano KRB and Census
- Print all PDF reports

The affected PDFs:
- impact-report-output.pdf
- action-checklist-output.pdf
- analysis-provenance-details-report-output.pdf

<img width="1437" alt="screen shot 2018-06-12 at 11 40 53" src="https://user-images.githubusercontent.com/1421861/41270460-9871ec8a-6e35-11e8-8400-46262dc65adf.png">
<img width="1339" alt="screen shot 2018-06-12 at 11 41 15" src="https://user-images.githubusercontent.com/1421861/41270461-989f0cba-6e35-11e8-9bdf-477cac32cdd5.png">

It works fine in QGIS 2.18/InaSAFE v4.4

### Expected Behaviour
A portrait report should be printed as a portrait.

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/b796dcfe0b50175c2dd7e7f18078150a76b48bc8

**Comment by ismailsunni** [comment]
Checked.
