### ISSUE TITLE
[Reporting] Open in Composer button doesnot work

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#21]
### Problem
On the print dialog, I tried to open in QGIS composer, but it doesn't show the QGIS composer. See gif below:
![open_composer_not_working](https://user-images.githubusercontent.com/1421861/41270652-9fc7e628-6e36-11e8-845a-2d12adab8051.gif)

It's working on QGIS 2.18/InaSAFE 4.4. See below:
![open_composer_working](https://user-images.githubusercontent.com/1421861/41270669-c6024860-6e36-11e8-8811-503dc7e1ba97.gif)

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/feb39a302e45be5e1d0fce9e750958fd64961a02
