### ISSUE TITLE
[Keyword Wizard] Broken UI in Multi Classification Step

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#24]
### Problem
Replicate:
- Load test data
- Select Flood Polygon
- Click next until multi-classification step
- Change the classification combo box
- The UI got broken
See below for the gif:
![broken_keywords_wizard_ui](https://user-images.githubusercontent.com/1421861/41273792-1a4b147a-6e45-11e8-9621-9ac9fe96d180.gif)

Note:
- rerun keyword wizard will make it worse (perhaps there are some un-deleted object)
- you need to restart QGIS to reset it again

**Comment by nyalldawson** [comment]
Should be fixed by https://github.com/inasafe/inasafe/pull/5000/commits/74006f22587be6ff51dfbf1ae6afc0c3881b9a27 - can you test and confirm please?

**Comment by timlinux** [comment]
@ismailsunni will you test the fix here please?

**Comment by ismailsunni** [comment]
Checked, LGTM
