### ISSUE TITLE
[OSM Downloader] Strange behaviour in after closing the dialog

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#26]
### Problem
After closing the dialog, suddenly from nowhere, there is a little dialog comes out:
See gif below for more explanation:
![osm_strange_behaviour](https://user-images.githubusercontent.com/1421861/41275127-149887c4-6e4a-11e8-8ff3-4407ec1cf49d.gif)

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/1072412a8c6f12ebe5bf931e93df68f5f66abcc4

**Comment by ismailsunni** [comment]
Checked.
