### ISSUE TITLE
[IFCW] Strange Mark when Choose in the Table

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#27]
### Problem
- Open Impact Function Wizard
- Choose any green cell
- It will give you apparently 3 circles inside the cell
<img width="1100" alt="screen shot 2018-06-12 at 14 11 48" src="https://user-images.githubusercontent.com/1421861/41275374-ee208104-6e4a-11e8-8eff-a731f2f64cc3.png">

**Comment by ismailsunni** [comment]
The next step is more hilarious :D 
<img width="1107" alt="screen shot 2018-06-12 at 14 17 43" src="https://user-images.githubusercontent.com/1421861/41275544-6f8e7642-6e4b-11e8-89af-b2dd3af6665d.png">

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/d38c0d77630fd7f215f09cb1aa45061fc6b195fb
