### ISSUE TITLE
[Reporting] Expression is not evaluated properly

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#28]
### Problem
Analysis: Flood Polygon and Population
InaSAFE 5:
<img width="1050" alt="screen shot 2018-06-12 at 14 26 39" src="https://user-images.githubusercontent.com/1421861/41276286-fd209768-6e4d-11e8-807d-73129b3b9a5f.png">

InaSAFE 4.4:
<img width="1002" alt="screen shot 2018-06-12 at 14 35 22" src="https://user-images.githubusercontent.com/1421861/41276298-04f9bf64-6e4e-11e8-8a19-d1acfb2dee29.png">

Note:
- I change the disclaimer text from the options menu (for both InaSAFE version)
- The date also not evaluated properly

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/309ada3128402e3ba53dd7a2ce4521e5fe250cd1
