### ISSUE TITLE
[IFCW] Not able to choose layer from disk

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#29]
### Problem
In the impact function keyword wizard, I got this kind of behavior. I am not able to choose layer from disk:
![ifcw_no_choose_layer](https://user-images.githubusercontent.com/1421861/41276622-fabd2846-6e4e-11e8-9ab3-63c4073e0a78.gif)

Compared to InaSAFE v4.4
<img width="1082" alt="screen shot 2018-06-12 at 14 43 50" src="https://user-images.githubusercontent.com/1421861/41276641-0b9b942c-6e4f-11e8-947b-e69c777fa6f3.png">

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/edc2e00eb9404e8ca056a35971b573b905db3b4c
