### ISSUE TITLE
[Minimum Needs Calculator] Description text is squeezed

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#32]
### Problem
In 5.0
<img width="599" alt="screen shot 2018-06-12 at 16 54 11" src="https://user-images.githubusercontent.com/1421861/41283642-51db5ca8-6e61-11e8-992f-d3bc348a085c.png">

In 4.4
<img width="640" alt="screen shot 2018-06-12 at 16 55 08" src="https://user-images.githubusercontent.com/1421861/41283668-63bf8d40-6e61-11e8-88bb-2a28fc097997.png">

```
Copy/paste some InaSAFE logs here if it was an error.
```

### Environment
* InaSAFE : 
* QGIS : 
* OS : 

* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist: 

* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by nyalldawson** [comment]
Fixed in https://github.com/inasafe/inasafe/pull/5000/commits/6b6dc138d2267c4e61bec6a0ec4bc11b3fa528e5

**Comment by ismailsunni** [comment]
Checked.
