### ISSUE TITLE
[Population Parameters] Changes is not saved after closing the option dialog

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#35]
### Problem
Replicate:
1. Open options dialog, go to population parameters tab
2. Change some value
3. Close the dialog
4. Restart QGIS
5. Check the value that you have changed, it's gone.

In QGIS 2.18 / InaSAFE 4.4 the changes are saved even after closing QGIS (written to QSettings)

**Comment by nyalldawson** [comment]
Fixed in https://github.com/inasafe/inasafe/pull/5000/commits/3ee4e08ffe12b59d3f4476914e511f9fe434028c

**Comment by ismailsunni** [comment]
Checked.
