### ISSUE TITLE
[Minimum Needs] Mess Up UI in Minimum Needs Manager Dialog

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#38]
### Problem
Reproduce:
- Open `Minimum Needs Manager`, edit one of the resources
- Click `Discard changes`
- The UI is little bit mess up, see GIF below

![mess-up-ui-minimum-needs](https://user-images.githubusercontent.com/1421861/41339724-c49c62c8-6f1f-11e8-989d-ab263d393b6a.gif)

**Comment by ismailsunni** [comment]
Same problem if you click save resource

**Comment by nyalldawson** [comment]
Not reproducible outside of OSX

**Comment by nyalldawson** [comment]
Closing following discussion with @timlinux as out of scope
