### ISSUE TITLE
[Minimum Needs] Change QGIS 2 reference when creating new minimum needs

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#39]
### Problem
Not a big problem (probably).
Replicate:
- Open `minimum needs manager`, click the `New` button
- It will go to `/Users/ismailsunni/.qgis2` directory

IMHO, it should go to more generic or QGIS3 related directory

![qgis2-reference](https://user-images.githubusercontent.com/1421861/41343227-3635e4ba-6f28-11e8-9941-a9d6e015d8ab.gif)

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/ff6fec79952fc776a28570d832d243875c889be8

**Comment by ismailsunni** [comment]
Checked.
