### ISSUE TITLE
[Minimum Needs] Minimum Needs files store in different location

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#40]
### Problem
Previously, it was stored in `~/.qgis2/inasafe/minimum_needs`, now it is moved to the current QGIS profile directory. We need to make sure all the help is properly changed.

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/ff6fec79952fc776a28570d832d243875c889be8

**Comment by ismailsunni** [comment]
Checked.
